### ISSUE TITLE
HTTP2 Pusher interface is broken

### ISSUE THREAD

**Issue by fabiocicerchia** [fabiocicerchia/go-proxy-cache#33]
seems that the HTTP2 Pusher interface is broken:

```
goproxycache_1  | 2020/11/30 19:28:05 http: panic serving *****:56882: runtime error: invalid memory address or nil pointer dereference
goproxycache_1  | goroutine 5938 [running]:
goproxycache_1  | net/http.(*conn).serve.func1(0xc000149220)
goproxycache_1  |       /usr/local/go/src/net/http/server.go:1801 +0x14f                                                                                                                                  goproxycache_1  | panic(0xc3fc20, 0x10f6aa0)
goproxycache_1  |       /usr/local/go/src/runtime/panic.go:975 +0x47a
goproxycache_1  | net/http.(*timeoutHandler).ServeHTTP(0xc0001c83c0, 0xda9580, 0xc00019f180, 0xc000546000)
goproxycache_1  |       /usr/local/go/src/net/http/server.go:3277 +0xe8b
goproxycache_1  | net/http.serverHandler.ServeHTTP(0xc00019ea80, 0xda9580, 0xc00019f180, 0xc000546000)
goproxycache_1  |       /usr/local/go/src/net/http/server.go:2843 +0xcb
goproxycache_1  | net/http.(*conn).serve(0xc000149220, 0xdaa640, 0xc000101100)
goproxycache_1  |       /usr/local/go/src/net/http/server.go:1925 +0x84d
goproxycache_1  | created by net/http.(*Server).Serve
goproxycache_1  |       /usr/local/go/src/net/http/server.go:2969 +0x5d4
```

more details on [HTTP/2 Adventure in the Go World](https://posener.github.io/http2/).

**Comment by fabiocicerchia** [comment]
> Although NGINX does not support HTTP2 backends, it can act as an HTTP2 frontend that translates requests back to origin servers as HTTP1.1, letting TLS termination and HTTP2 capabilities to itself.
> The tricky part of server push is knowing what to push - something that a proxy doesn’t know.

https://ops.tips/blog/nginx-http2-server-push/

If getting Link HTTP headers, when flag is active, convert to push requests.

Force communication with backend in http1.1 to avoid push in the same request (create a demo first).
